version: '3.8'

services:
  keycloak:
    build: .
    container_name: artixio-keycloak
    ports:
      - "8080:8080"
    environment:
      # Database configuration (PostgreSQL on local machine)
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
      KC_DB_USERNAME: sanatanupmanyu
      KC_DB_PASSWORD: ksDq2jazKmxxzv.VxXbkwR6Uxz
      
      # Keycloak admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      
      # Keycloak configuration
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      
      # Development settings
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      
    extra_hosts:
      # This allows the container to connect to localhost services
      - "host.docker.internal:host-gateway"
    
    depends_on:
      - postgres-check
    
    networks:
      - keycloak-network

  # Service to check if local PostgreSQL is accessible
  postgres-check:
    image: postgres:15-alpine
    container_name: postgres-check
    command: >
      sh -c "
        echo 'Checking PostgreSQL connection...' &&
        pg_isready -h host.docker.internal -p 5432 -U sanatanupmanyu &&
        echo 'PostgreSQL is ready!'
      "
    environment:
      PGPASSWORD: ksDq2jazKmxxzv.VxXbkwR6Uxz
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
